version: 2.1

ruby-image: &ruby-image cimg/ruby:2.7
env-vars: &env-vars
  BUNDLE_JOBS: 4
  RAILS_ENV: test
  RAKE_ENV: test
  BUNDLE_PATH: /home/circleci/project/vendor/bundle
  GEM_PATH: /home/circleci/project/vendor/bundle/ruby/2.7.0

executors:
  ruby-executor:
    docker:
      - image: *ruby-image
        environment: *env-vars

commands:
  setup:
    description: checkout code, restore cache, install dependencies, save cache
    steps:
      - checkout

      - restore_cache:
          keys:
          - potassium-vendor-bundle-{{ .Branch }}
          - potassium-vendor-bundle-master
          - potassium-vendor-bundle

      - run:
          name: Install bundle dependencies
          command: |
            gem install bundler:2.1.4
            bundle _2.1.4_ install

      - run:
          name: Install node and yarn
          command: |
            curl -sL https://deb.nodesource.com/setup_$(cat .node-version).x | sudo -E bash -
            sudo apt-get install -y nodejs
            curl -o- -sL https://yarnpkg.com/install.sh | bash
            sudo ln -s $HOME/.yarn/bin/yarn /usr/local/bin/yarn

      - save_cache:
          key: potassium-vendor-bundle-{{ .Branch }}
          paths:
            - vendor/bundle

jobs:
  test:
    parallelism: 6
    executor: ruby-executor
    steps:
      - setup

      - run:
          name: Run rspec
          command: |
            RSPEC_JUNIT_ARGS="-r rspec_junit_formatter -f RspecJunitFormatter -o test_results/rspec.xml"
            RSPEC_GENERAL_ARGS="-f progress --no-color -p 10"
            SPLIT_ARGS="$(circleci tests glob spec/**/*_spec.rb | circleci tests split --split-by=timings)"
            bundle exec rspec $RSPEC_GENERAL_ARGS $RSPEC_JUNIT_ARGS $SPLIT_ARGS

      - store_test_results:
          path: test_results

  lint:
    executor: ruby-executor
    steps:
      - setup

      - run:
          name: Install reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ./bin

      - run:
          name: Get files to lint
          command: git diff origin/master --name-only --diff-filter=d > tmp/files_to_lint

      - run:
          name: Run rubocop
          shell: /bin/bash
          command: |
            cat tmp/files_to_lint | grep -E '.+\.(rb)$' | xargs bundle exec rubocop --force-exclusion \
            | ./bin/reviewdog -reporter=github-pr-review -f=rubocop

  deploy:
    executor: ruby-executor
    steps:
      - setup

      - run:
          name: Setup rubygems
          command: bash .circleci/setup-rubygems.sh

      - run:
          name: Publish to rubygems
          command: |
            gem build potassium.gemspec
            version_tag=$(git describe --tags)
            gem push potassium-${version_tag#v}.gem

workflows:
  test_and_lint:
    jobs:
      - test
      - lint:
          context: org-global
      - deploy:
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
